### PR TITLE
Fixes #63: Improve number of fields check

### LINKED ISSUE #63: required column bug
hello
i'm testing this package to valid CSV ( obviously) 

i maybe found a bug 

for example i have 4 columns, the 2 first are required

```
const CSVConfig = {
  headers: [
    {name: 'id', inputName: 'id', required: true, requiredError, unique: true, uniqueError},
    {name: 'content', inputName: 'content', required: true, requiredError},
    {name: 'exa', inputName: 'exa', required: false},
    {name: 'exb', inputName: 'exb', required: false},
  ]
}
```
the following CSV don't throw error even if last row have only ONE column ,But it should throw error because missing the second column :
```
"id","content","exa","exb"
"www.agent_de_fabrication.com15"
```

this throw an error : 

```
"id","content","exa","exb"
"www.agent_de_fabrication.com15",
```

I'm missing an option ? 

thanks for your hard work

### PR DESCRIPTION
**Pull request by reBirthLab**

### CODE REVIEW

**Comment by shystruk** [comment]
@reBirthLab thanks for the contribution

**Comment by reBirthLab** [comment]
@shystruk this logic should only check the structure of the row. The number of fields should always match the number of columns in the header regardless required they or not. Then afterwards, there is another check in the code where we check the field content and if it is required, we add error to the list.
For example, if CSV has the header:
`First name (optional);Last name (required);Address (optional)`,
the valid row should be:
`;Smith;`
Reading the code, it should work like that with the change I suppose. But I will check it practically tomorrow.

**Comment by reBirthLab** [comment]
@shystruk I checked how it works and couldn't find any issues with the required fields. It works as described above. 

Could you please give an example CSV that would demonstrate the issue?

**Comment by shystruk** [comment]
Try to run a test.js file and see if all tests passed

**Pull request merged**
